"""init

Revision ID: 6fa94116b581
Revises: 
Create Date: 2026-04-05 02:22:43.332609
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6fa94116b581'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_access_agent', table_name='agent_access')
    op.drop_index('ix_agent_access_granted_to', table_name='agent_access')
    op.drop_index('ix_agent_responses_session', table_name='agent_responses')
    op.drop_index('ix_language_samples_agent_lang', table_name='language_samples')
    op.drop_column('language_samples', 'context_type')
    op.alter_column('memories', 'section',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('memories', 'transcript_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index('ix_memories_agent_active', table_name='memories')
    op.drop_index('ix_memories_agent_reinforcement', table_name='memories')
    op.drop_index('ix_memories_agent_weight', table_name='memories')
    op.drop_index('ix_neo_packages_agent_id', table_name='neo_packages')
    op.drop_index('ix_neo_packages_user_id', table_name='neo_packages')
    op.drop_index('uq_neo_packages_agent_key', table_name='neo_packages', postgresql_where='((is_active = true) AND (package_key IS NOT NULL))')
    op.drop_index('uq_neo_packages_agent_slot', table_name='neo_packages', postgresql_where='(is_active = true)')
    op.drop_constraint('fk_neo_packages_user_id_users', 'neo_packages', type_='foreignkey')
    op.drop_constraint('fk_neo_packages_agent_id_agent_profiles', 'neo_packages', type_='foreignkey')
    op.create_foreign_key(op.f('fk_neo_packages_agent_id_agent_profiles'), 'neo_packages', 'agent_profiles', ['agent_id'], ['id'])
    op.create_foreign_key(op.f('fk_neo_packages_user_id_users'), 'neo_packages', 'users', ['user_id'], ['id'])
    op.drop_index('ix_pattern_abstractions_agent_id', table_name='pattern_abstractions')
    op.alter_column('personality_survey', 'past_locations',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_column('personality_survey', 'pronoun_friend')
    op.drop_column('personality_survey', 'pronoun_lover')
    op.drop_column('personality_survey', 'pronoun_stranger')
    op.drop_column('personality_survey', 'pronoun_older')
    op.drop_column('personality_survey', 'pronoun_family')
    op.drop_column('personality_survey', 'pronoun_close_friend')
    op.drop_column('personality_survey', 'pronoun_coworker')
    op.drop_column('personality_survey', 'pronoun_younger')
    op.alter_column('relationship_profiles', 'zone',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_rel_profiles_agent', table_name='relationship_profiles')
    op.drop_index('ix_rel_profiles_agent_zone', table_name='relationship_profiles')
    op.drop_column('relationship_profiles', 'allowed_topics')
    op.drop_column('relationship_profiles', 'voice_extracted_at')
    op.drop_column('relationship_profiles', 'swearing_level')
    op.drop_index('ix_rel_roles_agent', table_name='relationship_roles')
    op.drop_index('ix_rel_roles_type', table_name='relationship_roles')
    op.drop_index('ix_rel_types_agent', table_name='relationship_types')
    op.drop_index('ix_slang_user_language', table_name='slang_dictionary')
    op.alter_column('voice_samples', 'language_slot',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=10),
               nullable=True,
               existing_server_default=sa.text("'native'::character varying"))
    op.drop_constraint('uq_voice_samples_user_slot', 'voice_samples', type_='unique')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_voice_samples_user_slot', 'voice_samples', ['user_id', 'language_slot'])
    op.alter_column('voice_samples', 'language_slot',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'native'::character varying"))
    op.create_index('ix_slang_user_language', 'slang_dictionary', ['user_id', 'language', 'is_active'], unique=False)
    op.create_index('ix_rel_types_agent', 'relationship_types', ['agent_id'], unique=False)
    op.create_index('ix_rel_roles_type', 'relationship_roles', ['type_id'], unique=False)
    op.create_index('ix_rel_roles_agent', 'relationship_roles', ['agent_id'], unique=False)
    op.add_column('relationship_profiles', sa.Column('swearing_level', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True))
    op.add_column('relationship_profiles', sa.Column('voice_extracted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('relationship_profiles', sa.Column('allowed_topics', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=True))
    op.create_index('ix_rel_profiles_agent_zone', 'relationship_profiles', ['agent_id', 'zone'], unique=False)
    op.create_index('ix_rel_profiles_agent', 'relationship_profiles', ['agent_id'], unique=False)
    op.alter_column('relationship_profiles', 'zone',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('personality_survey', sa.Column('pronoun_younger', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('personality_survey', sa.Column('pronoun_coworker', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('personality_survey', sa.Column('pronoun_close_friend', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('personality_survey', sa.Column('pronoun_family', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('personality_survey', sa.Column('pronoun_older', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('personality_survey', sa.Column('pronoun_stranger', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('personality_survey', sa.Column('pronoun_lover', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('personality_survey', sa.Column('pronoun_friend', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('personality_survey', 'past_locations',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.create_index('ix_pattern_abstractions_agent_id', 'pattern_abstractions', ['agent_id'], unique=False)
    op.drop_constraint(op.f('fk_neo_packages_user_id_users'), 'neo_packages', type_='foreignkey')
    op.drop_constraint(op.f('fk_neo_packages_agent_id_agent_profiles'), 'neo_packages', type_='foreignkey')
    op.create_foreign_key('fk_neo_packages_agent_id_agent_profiles', 'neo_packages', 'agent_profiles', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_neo_packages_user_id_users', 'neo_packages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('uq_neo_packages_agent_slot', 'neo_packages', ['agent_id', 'slot_number'], unique=True, postgresql_where='(is_active = true)')
    op.create_index('uq_neo_packages_agent_key', 'neo_packages', ['agent_id', 'package_key'], unique=True, postgresql_where='((is_active = true) AND (package_key IS NOT NULL))')
    op.create_index('ix_neo_packages_user_id', 'neo_packages', ['user_id'], unique=False)
    op.create_index('ix_neo_packages_agent_id', 'neo_packages', ['agent_id'], unique=False)
    op.create_index('ix_memories_agent_weight', 'memories', ['agent_id', 'feeling_weight'], unique=False)
    op.create_index('ix_memories_agent_reinforcement', 'memories', ['agent_id', 'reinforcement_count', 'feeling_weight'], unique=False)
    op.create_index('ix_memories_agent_active', 'memories', ['agent_id', 'is_active'], unique=False)
    op.alter_column('memories', 'transcript_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('memories', 'section',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.add_column('language_samples', sa.Column('context_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index('ix_language_samples_agent_lang', 'language_samples', ['agent_id', 'language'], unique=False)
    op.create_index('ix_agent_responses_session', 'agent_responses', ['agent_id', 'session_key', 'created_at'], unique=False)
    op.create_index('ix_agent_access_granted_to', 'agent_access', ['granted_to_user_id'], unique=False)
    op.create_index('ix_agent_access_agent', 'agent_access', ['agent_id'], unique=False)
    # ### end Alembic commands ###
